### ISSUE TITLE
Refactor package and module names and structure

### ISSUE THREAD

**Issue by DaJansenGit** [BIM2SIM/bim2sim#544]
# Todo
* [x] create own top level package like `meta_structure.py` and move into `element.py` and content of `elements` package into it 
* [x] delete empty folders in kernel: `building` and `cfd`
* [ ] put top level files that are kernel files into kernel
* [x] remove enrichment_data package which only holds two functions
