### ISSUE TITLE
Split plugins from kernel

### ISSUE THREAD

**Issue by DaJansenGit** [BIM2SIM/bim2sim#87]
We have to make sure that no plugin or workflow specific code is imported or written in kernel modules. On the other hand all code that is generic and usable by all workflows shouldn't be implemented in the plugins or specific workflows. This is currently the case here for [example](https://git-ce.rwth-aachen.de/ebc/projects/EBC0438_BMWi_BIM2SIM_GES/bim2sim-coding/-/blob/development/MainLib/bim2sim/kernel/attribute.py#L117-137)

### ToDos:
* [ ] split Plugins and put them into individual repositorys
* [x] rework imports for new placement of plugins
* [x] move bim2sim folder one level up
* [x] create folder plugins in bim2sim and add all "internal/buildin" plugins
* [x] move external hkesim plugin into own repository
* [ ] for development: in every external plugin repository we have implemented the main bim2sim tool as submodule
* [ ] create installation process (setup.py) for each plugin

### Folder Structure
* [x] all plugins should have the same folder structure:
  * Repository_folder

    * bim2sim_xxx
       * task 
       * assets
       * ... (see bim2sim mainlib)
    * test
      * integration
      * unit
    * requirements.txt
    * dockerfiles if existing (env<PluginName>.Dockerfile)

### How to handle tests:
* We move example files to another place (different repo only for example files or sciebo etc.)
* We create an example folder in bim2sim main folder and each plugin folder
* submodule or other repo will hold n+1 folders: bim2sim_main, Plugin_1, ... Plugin_n
* if submodule:
  * no .gitignore needed
* else:
  * put folders on .gitignore
* David will check how to handle and cache such large files for the CI 

### Finalize
* [ ] test if plugins are found by main repository
* [ ] split docker images and CI pipelines for all Plugins and Core

This process should be done by anybody for their own plugins
